### ISSUE TITLE
The Statistical Report 11 is not known.

### ISSUE THREAD

**Issue by xmacan** [Cacti/plugin_flowview#203] opened 2024-08-12 14:10 UTC
Sorry, we could not process your last action.

The Statistical Report 11 is not known. Please open a bug on GitHub

actual develop version

**Comment by TheWitness** [comment] 2024-08-13 13:05
This might be a duplicate of #196

**Comment by TheWitness** [comment] 2024-08-13 22:39
Fixed now.

**Closed as completed by TheWitness** 2024-08-13 22:39 UTC
Labels: bug, resolved, QA
